version: 2
accept_configuration:
  condition: and
  conditions:
    - condition: property
      property: features
      not_contains_value: Disable
    - condition: property
      property: target.osVersion
      not_contains_value: QNX_800

instructions:
  Build:
    - type: EnvironmentVariable
      variableName: VERIFY_SOURCE_SBOM
      variableValue: "ON"
    - !include "{{qt/qtbase}}/coin_module_build_template_v2.yaml"

  Test:
    - !include "{{qt/qtbase}}/coin_module_test_template_v3.yaml"
    - !include "{{qt/qtbase}}/coin_module_test_docs.yaml"
